linters:
  enable:
    - errcheck
    - forbidigo
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused

  disable:
    - gofumpt
    - depguard

  presets:
    - format
    - import

linters-settings:
  govet:
    disable:
        # Unkeyed primitive.E and timestamp fields are used extensively in code taken from
        # mongosync.
        - composites
  forbidigo:
    forbid:
      - p: context\.Background
        msg: Use contextplus.
      - p: context\.WithCancel(?:Cause)?
        msg: Use contextplus.
      - p: context\.WithTimeout(?:Cause)?
        msg: Use contextplus.
      - p: context\.WithDeadline(?:Cause)?
        msg: Use contextplus.
