version: "2"
linters:
  enable:
    - forbidigo
    - gomodguard
  disable:
    - depguard
  settings:
    forbidigo:
      forbid:
        - pattern: context\.WithCancel(?:Cause)?
          msg: Use contextplus.
        - pattern: context\.WithTimeout(?:Cause)?
          msg: Use contextplus.
        - pattern: context\.WithDeadline(?:Cause)?
          msg: Use contextplus.
        - pattern: errgroup.WithContext
          msg: Use contextplus.
    govet:
      disable:
        # Unkeyed primitive.E and timestamp fields are used extensively in code taken from
        # mongosync.
        - composites
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
