version: "2"
linters:
  enable:
    - forbidigo
    - gomodguard
    - govet
    - gocritic
  disable:
    - depguard
  settings:
    forbidigo:
      forbid:
        - pattern: context\.WithCancel(?:Cause)?
          msg: Use contextplus.
        - pattern: context\.WithTimeout(?:Cause)?
          msg: Use contextplus.
        - pattern: context\.WithDeadline(?:Cause)?
          msg: Use contextplus.
        - pattern: errgroup.WithContext
          msg: Use contextplus.
    gocritic:
      disable-all: true
      enabled-checks:
        - ruleguard
      settings:
        ruleguard:
          rules: "${base-path}/gorules/*.go"
          failOn: all
    govet:
      disable:
        # Unkeyed primitive.E and timestamp fields are used extensively in code taken from
        # mongosync.
        - composites
  exclusions:
    generated: lax
    presets:
      - std-error-handling
formatters:
  enable:
    - gci
    - gofmt
    - goimports
